user = "azureuser"
password = "P4ssW0rD@123"
location = "eastus"
environment = "atividade-2"
client_id = "client_id"
client_secret = "client_secret"
tenant_id = "tenant_id"
subscription_id = "subscription_id"